logging:
  level:
    root: INFO
    com.crediya.auth: DEBUG
    org.springframework.security: DEBUG
server:
  port: 8081
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "crediya-auth"
    version: 1.0.0
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  liquibase:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET_KEY}
adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    schema: "public"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}
route:
  path:
    auth:
      login: "/api/v1/auth/log-in"
    user:
      registerUser: "/api/v1/users"
      getUserByIdentityCardNumber: "/api/v1/users/{identity_card_number}"
      getUsers: "/api/v1/users"
