app:
  version: 1.0.0
logging:
  level:
    root: INFO
    com.crediya.auth: DEBUG
server:
  port: 8081
spring:
  application:
    name: "crediya-auth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/crediya
    user: admin
    password: admin123
    change-log: classpath:/db/changelog/db.changelog-master.yaml
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya"
    schema: "public"
    username: "admin"
    password: "admin123"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
